name: Java Release Workflow
on:
  push:
    branches: [ main ]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Build the project
      - name: Build with Maven
        run: mvn clean package assembly:single

      # Create a release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          RELEASE_TITLE: "Release v${GITHUB_REF##*/}"
          RELEASE_NOTES: "Automated release from ${GITHUB_REF}"
        with:
          generate_notes: true

      # Upload artifact to release
      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: target/
          retention-days: 1

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/${project.artifactId}-${project.version}-jar-with-dependencies.jar
          asset_name: ${project.artifactId}-${project.version}-jar-with-dependencies.jar
          asset_type: application/java-archive
