name: Build and Release Maven Project

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package assembly:single

      - name: Find the JAR with dependencies
        id: find_jar
        run: echo "JAR_FILE=$(ls target/*-with-dependencies.jar | head -n 1)" >> $GITHUB_ENV

      - name: Upload artifact to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.JAR_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
